services:
  discord-bot:
    build: .
    image: lucy-chan:latest
    pull_policy: build

    container_name: lucy-chan
    restart: unless-stopped

    working_dir: /app
    command: npm start

    environment:
      TZ: America/Sao_Paulo
      TOKEN: ${TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID}

    volumes:
      - /DATA/AppData/lucy-chan/data:/app/data